version: '2'
services:
  web:
    image: docker-physijs-tutorial/latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./www:/var/www
      - ./log:/var/log/apache2
    environment:
      - API_TOKEN=xxxx
    tty: true
